name: resumaker
services:
  ci-resume: &ci
    profiles: ["ci"]
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment: &env
      FILE: "resume.pdf"
      TEXINPUTS: ".:./private//:./info//:/out//:"
      HOST_USER: "${UID}"
      HOST_GROUP: "${GID}"
    volumes:
      - ./out:/out
      - ./latex:/app
  ci-cover:
    <<: *ci
    environment:
      <<: *env
      FILE: "cover.pdf"
  ci-main:
    <<: *ci
    environment:
      <<: *env
      FILE: "main.pdf"
    depends_on:
      ci-cover:
        condition: service_completed_successfully
      ci-resume:
        condition: service_completed_successfully


  run-resume: &run
    <<: *ci
    profiles: ["dev"]
    environment:
      <<: *env
      FILE: "resume.tex"
    healthcheck:
      test: ["CMD-SHELL", "ls /out/$${FILE%%.*}.pdf"]
      start_period: 3s
      interval: 3s
      retries: 3
  run-cover:
    <<: *run
    environment:
      <<: *env
      FILE: "cover.tex"
  run-main:
    <<: *run
    environment:
      <<: *env
      FILE: "main.tex"
    depends_on:
      run-cover:
        condition: service_healthy
      run-resume:
        condition: service_healthy
