name: resumaker
services:
  build-main:
    profiles: ["build"]
    build: &build
      context: .
    environment: &env
      FILENAME: "main.pdf"
      TEXINPUTS: ".:./private//:./info//:./out//:"
      HOST_USER: "${UID}"
      HOST_GROUP: "${GID}"
    volumes:
      - ./out:/app/out

  run-resume: &default-run
    profiles: ["dev"]
    build: *build
    environment:
      <<: *env
      FILENAME: "resume.tex"
    healthcheck:
      test: ["CMD-SHELL", "ls out/$${FILENAME%%.*}.pdf"]
      interval: 3s
      retries: 3
    volumes:
      - .:/app
  run-cover:
    <<: *default-run
    environment:
      <<: *env
      FILENAME: "cover.tex"
  run-main:
    <<: *default-run
    environment:
      <<: *env
      FILENAME: "main.tex"
    depends_on:
      run-cover:
        condition: service_healthy
      run-resume:
        condition: service_healthy
